// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface CarouselStoryblok {
  carousel_items?: (CarouselStoryblok | FeatureStoryblok | GridStoryblok | PageStoryblok | TeaserStoryblok)[];
  component: "carousel";
  _uid: string;
  [k: string]: any;
}

export interface FeatureStoryblok {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: any;
}

export interface GridStoryblok {
  columns?: (CarouselStoryblok | FeatureStoryblok | GridStoryblok | PageStoryblok | TeaserStoryblok)[];
  component: "grid";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  body?: (CarouselStoryblok | FeatureStoryblok | GridStoryblok | PageStoryblok | TeaserStoryblok)[];
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface TeaserStoryblok {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: any;
}
